import { HttpInterceptorFn } from '@angular/common/http';
import { inject } from '@angular/core';
// import { UserService } from '../user.service';
import { from, switchMap } from 'rxjs';

export const tokenInterceptor: HttpInterceptorFn = (req, next) => {
  let token: string =
    'eyJhbGciOiJFUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJKRHlvU2NsRWI4UE9ydkp4UlFYYzRoTVNmT3YzUUFYbGRYSG1wVEJxNXlzIn0.eyJleHAiOjE3MTQwNzQ1NjAsImlhdCI6MTcxNDAzODU2MCwianRpIjoiYTg2YWZjNjQtMTg4OC00ZDU2LWJjYTItNDQ1MTQ0ZDlhODVjIiwiaXNzIjoiaHR0cHM6Ly9rZXljbG9hay5zdW1taXRzeW5jLm1lc2NodGVyLm1lL3JlYWxtcy9zdW1taXQtc3luYyIsImF1ZCI6WyJyZWFsbS1tYW5hZ2VtZW50Iiwic3VtbWl0c3luYyIsImFjY291bnQiXSwic3ViIjoiNzI1NGRkNWUtZGM4MC00M2FlLWE3YjEtZTFiNTg5MGUwNDg0IiwidHlwIjoiQmVhcmVyIiwiYXpwIjoic3VtbWl0LXN5bmMtYmZmIiwic2Vzc2lvbl9zdGF0ZSI6IjNlYTQ1Y2IzLWI4ZjYtNDhhNS1iOTg5LTg0ZWE3YTFhNjk3MSIsImFjciI6IjEiLCJhbGxvd2VkLW9yaWdpbnMiOlsiaHR0cDovLzEyNy4wLjAuMToqIiwiaHR0cDovL2xvY2FsaG9zdDoqIl0sInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLXN1bW1pdC1zeW5jIiwib2ZmbGluZV9hY2Nlc3MiLCJ1bWFfYXV0aG9yaXphdGlvbiJdfSwicmVzb3VyY2VfYWNjZXNzIjp7InJlYWxtLW1hbmFnZW1lbnQiOnsicm9sZXMiOlsidmlldy1yZWFsbSIsIm1hbmFnZS11c2VycyIsInZpZXctdXNlcnMiLCJxdWVyeS1ncm91cHMiLCJxdWVyeS11c2VycyJdfSwic3VtbWl0c3luYyI6eyJyb2xlcyI6WyJhZG1pbiJdfSwiYWNjb3VudCI6eyJyb2xlcyI6WyJtYW5hZ2UtYWNjb3VudCIsIm1hbmFnZS1hY2NvdW50LWxpbmtzIiwidmlldy1wcm9maWxlIl19fSwic2NvcGUiOiJvcGVuaWQgZW1haWwgcHJvZmlsZSIsInNpZCI6IjNlYTQ1Y2IzLWI4ZjYtNDhhNS1iOTg5LTg0ZWE3YTFhNjk3MSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwibmFtZSI6IlRlc3QgQWRtaW4iLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJ0ZXN0X2FkbWluIiwiZ2l2ZW5fbmFtZSI6IlRlc3QiLCJmYW1pbHlfbmFtZSI6IkFkbWluIn0.YdvxXsqWRby3BeCy8vhpXQEoHnzFUAVeiPSvsv3oGjJf4zJN7LRQKNuMScmeLAHWBfkci3qihEewNoStc5dMcw';

  //   const userService = inject(UserService);

  console.log('injecting token');
  return next(
    req.clone({
      headers: req.headers.set('Authorization', `Bearer ${token}`),
    })
  );
};
